# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_bi_st <- function(v0, m, M) {
    .Call('JSM_calc_bi_st', PACKAGE = 'JSM', v0, m, M)
}

calc_expM2 <- function(A) {
    invisible(.Call('JSM_calc_expM2', PACKAGE = 'JSM', A))
}

calc_M1_a_M2_Hadamard <- function(M1, M2, a, v) {
    invisible(.Call('JSM_calc_M1_a_M2_Hadamard', PACKAGE = 'JSM', M1, M2, a, v))
}

calc_M1_M2_Hadamard_a <- function(A1, A2, v3, a) {
    .Call('JSM_calc_M1_M2_Hadamard_a', PACKAGE = 'JSM', A1, A2, v3, a)
}

calc_M1_M2_Hadamard <- function(M1, M2) {
    invisible(.Call('JSM_calc_M1_M2_Hadamard', PACKAGE = 'JSM', M1, M2))
}

calc_M1_M2_M3_Hadamard <- function(M1, M2, M3, v) {
    invisible(.Call('JSM_calc_M1_M2_M3_Hadamard', PACKAGE = 'JSM', M1, M2, M3, v))
}

calc_M1timesM2v <- function(M1, M2, v) {
    .Call('JSM_calc_M1timesM2v', PACKAGE = 'JSM', M1, M2, v)
}

calc_muB <- function(BSold, VY, Xst, Zst, Yst, betaold) {
    .Call('JSM_calc_muB', PACKAGE = 'JSM', BSold, VY, Xst, Zst, Yst, betaold)
}

calc_muBMult <- function(BSold, VY, BTg, Yst) {
    .Call('JSM_calc_muBMult', PACKAGE = 'JSM', BSold, VY, BTg, Yst)
}

calc_mult_rowsum1 <- function(v, u, M, A) {
    .Call('JSM_calc_mult_rowsum1', PACKAGE = 'JSM', v, u, M, A)
}

calc_mult_rowsum2 <- function(v, L, M, A) {
    .Call('JSM_calc_mult_rowsum2', PACKAGE = 'JSM', v, L, M, A)
}

calc_mult_rowsum3 <- function(v, B, M, A, ncb2) {
    .Call('JSM_calc_mult_rowsum3', PACKAGE = 'JSM', v, B, M, A, ncb2)
}

calc_M_v <- function(v, M) {
    .Call('JSM_calc_M_v', PACKAGE = 'JSM', v, M)
}

calc_MVND <- function(x, mu, K) {
    .Call('JSM_calc_MVND', PACKAGE = 'JSM', x, mu, K)
}

calc_rowsum <- function(v, M) {
    .Call('JSM_calc_rowsum', PACKAGE = 'JSM', v, M)
}

calc_rowsum_mult <- function(v, u, M) {
    .Call('JSM_calc_rowsum_mult', PACKAGE = 'JSM', v, u, M)
}

calc_tapply_vect_sum <- function(v1, v2) {
    .Call('JSM_calc_tapply_vect_sum', PACKAGE = 'JSM', v1, v2)
}

calc_v_a <- function(v, a) {
    invisible(.Call('JSM_calc_v_a', PACKAGE = 'JSM', v, a))
}

calc_VB <- function(M1, M2, M3) {
    .Call('JSM_calc_VB', PACKAGE = 'JSM', M1, M2, M3)
}

calc_VY <- function(M, A, b) {
    .Call('JSM_calc_VY', PACKAGE = 'JSM', M, A, b)
}

fast_lapply_length <- function(input1, input2, Ind) {
    .Call('JSM_fast_lapply_length', PACKAGE = 'JSM', input1, input2, Ind)
}

fast_rbind_lapply_outerprod <- function(input) {
    .Call('JSM_fast_rbind_lapply_outerprod', PACKAGE = 'JSM', input)
}

